### PR TITLE
Speed up From trait, added CI

### PR DESCRIPTION
**Pull request by nyurik**
* CI will automatically test the quality of the code
* From is now much faster, relying on Rust to validate everything
* pre-commit hook validates everything too to avoid breaking the code

### CODE REVIEW

**Comment by nyurik** [comment]
@matthewjberger hi, any thoughts about this? friendly ping :)

**Review by matthewjberger — APPROVED** [review]

**Comment by nyurik** [comment]
@matthewjberger thx for merging!  Should I submit another PR for bumping the version and publishing?  Or do you want me to do the actual publishing? (I don't think I am part of the repo for that, and I don't want to take a credit away from you :) )

**Comment by matthewjberger** [comment]
Thank you for the reminder! I just published the next version on crates.io 🚀

**Comment by nyurik** [comment]
Thank you!  Sorry to be a pest :)

**Pull request merged**
